import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NextAuthProvider} from "./Provider"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mongodber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <NextAuthProvider>
          <div className="max-w-3xl mx-auto bg-slate-400">
            {/* <Navbar /> */}
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
